<Project Sdk="Microsoft.NET.Sdk">

  <!-- 1000 Hz publisher on the default interface/domain. -->
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <AssemblyName>dart_publisher</AssemblyName>
    <RootNamespace>DartPublisher</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../Dart.cs" />
    <None Include="../runtimes/**/native/*" Link="%(Filename)%(Extension)">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
